version: '3'
services:
   selenium-hub:
      image: selenium/hub:3.141.59
      container_name: selenium-hub
      ports:
      - 4444:4444
   chrome:
      image: selenium/node-chrome:3.141.59-20210804
      volumes:
      - /dev/shm:/dev/shm
      depends_on:
      - selenium-hub
      environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
      ports:
#    ports:
#      - "9001:5900"
      - 5900-5905:5900